# Example:
# --config benchmarks.yml --scenario proxy-yarp --profile aspnet-physical

imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BenchmarksDriver2/benchmarks.proxy.yml

jobs:
  yarp:
    source:
      repository: https://github.com/microsoft/reverse-proxy.git
      branchOrCommit: halter73/benchmark-testing
      project: samples/BenchmarkApp/BenchmarkApp.csproj
    readyStateText: Application started.
    variables:
    arguments: '--urls {{serverUri}}:{{serverPort}} --backendUrls {{downstreamUri}}'
    port: 5000

scenarios:
  proxy-yarp:
    downstream:
      job: downstream
    application:
      job: yarp
    warmup:
      job: bombardier
      variables:
        serverPort: 5000
    load:
      job: bombardier
      variables:
        serverPort: 5000
